site_name: GeoGuide in China
site_url: https://www.geoguide.top/
repo_url: https://github.com/Konano/geoguide-in-china
repo_name: Geoguide in China
theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  # features:
  #   - navigation.tabs
  #   - navigation.tabs.sticky
  features:
    - navigation.instant
    - navigation.instant.prefetch
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # scheme: youtube
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # scheme: youtube
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
# nav:
#   - index.md
#   - index2.md
# extra_css:
#   - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
